DCWP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('drcontrol/', include('drcontrol.urls')),
    path('', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns =[
    path('', views.Login.as_view(), name='login'),
    path('', views.Logout.as_view(), name='logout'),
]

drcontrol/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="drcontrol"

urlpatterns = [
    path('top/', views.top, name='top'),
    path('dronecontrol/', views.dronecontrol, name='dronecontrol'),
    path('calendar/', views.calendar, name='calendar'),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


@python_2_unicode_compatible
class AuthUserManager(BaseUserManager):
    def create_user(self, username, email, password, last_name, first_name):
        """
        ユーザ作成

        :param username: ユーザID
        :param email: メールアドレス
        :param password: パスワード
        :param last_name: 苗字
        :param first_name: 名前
        :return: AuthUserオブジェクト
        """
        if not email:
            raise ValueError('Users must have an email')
        if not username:
            raise ValueError('Users must have an username')

        user = self.model(username=username,
                          email=email,
                          password=password,
                          last_name=last_name,
                          first_name=first_name)
        user.is_active = True
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, last_name, first_name):
        """
        スーパーユーザ作成

        :param username: ユーザID
        :param email: メールアドレス
        :param password: パスワード
        :param last_name: 苗字
        :param first_name: 名前
        :return: AuthUserオブジェクト
        """
        user = self.create_user(username=username,
                                email=email,
                                password=password,
                                last_name=last_name,
                                first_name=first_name)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


@python_2_unicode_compatible
class AuthUser(AbstractBaseUser, PermissionsMixin):
    """
    ユーザ情報を管理する
    """
    class Meta:
        verbose_name = 'ユーザ'
        verbose_name_plural = 'ユーザ'

    def get_short_name(self):
        """
        ユーザの苗字を取得する

        :return: 苗字
        """
        return self.last_name

    def get_full_name(self):
        """
        ユーザのフルネームを取得する

        :return: 苗字 + 名前
        """
        return self.last_name + self.first_name

    username = models.CharField(verbose_name='ユーザID',
                                unique=True,
                                max_length=30)
    last_name = models.CharField(verbose_name='苗字',
                                 max_length=30,
                                 default=None)
    first_name = models.CharField(verbose_name='名前',
                                  max_length=30,
                                  default=None)
    email = models.EmailField(verbose_name='メールアドレス',
                              null=True,
                              default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(verbose_name='有効フラグ',
                                    default=True)
    is_staff = models.BooleanField(verbose_name='管理サイトアクセス権限',
                                   default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'last_name', 'first_name']
    objects = AuthUserManager()

    def __str__(self):
        return self.last_name + ' ' + self.first_name

drcontrol/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm 


class LoginForm(AuthenticationForm):
    """ログオンフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label 

drcontrol/forms.py
from django import forms
from django.conf import settings
from django.core.files.storage import default_storage
import os, random, string


class UploadForm(forms.Form):
    """PDFアップロード用フォームの定義
       saveメソッドはアップロードしたPDFを一時フォルダに保存する。
    """
    document = forms.FileField(label="PDFアップロード",
        widget=forms.ClearableFileInput(attrs={'multiple': True}), 
        )


    def save(self):
        upload_files = self.files.getlist('document')
        temp_dir = os.path.join(settings.MEDIA_ROOT, self.create_dir(10))   #一時フォルダの生成
        for pdf in upload_files:
            default_storage.save(os.path.join(temp_dir, pdf.name), pdf)   #一時フォルダにPDFを保存
        return temp_dir
    
    def create_dir(self, n):
        """一時フォルダ名生成関数"""
        return 'pdf\\' + ''.join(random.choices(string.ascii_letters + string.digits, k=n))

accounts/views.py
from django.shortcuts import render

#ログイン機能
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'accounts/login.html'

drcontrol/views.py
from django.shortcuts import render
from django.shortcuts import redirect

# Create your views here.
def top(request):
    return render(request, 'drcontrol/top.html') 

def dronecontrol(request):
    return render(request, 'drcontrol/dronecontrol.html')

def calendar(request):
    return render(request, 'drcontrol/calendar.html')

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Drone Control</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <b>Drone Control</b>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg"><b>ログイン画面</b></p>

      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group has-feedback">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">

          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">ログイン</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

<p style="text-align:center;margin-top: -100px;">Username : test01 <br> Password : password</p>
  <!-- jQuery 3 -->
  <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <!-- iCheck -->
  <script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
</body>
</html>

templates/drcontrol/calendar.html
{% extends './base.html' %}
{% block content %}



  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        カレンダー
        <small></small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>ホーム</a></li>
        <li class="active">カレンダー</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-3">
          <div class="box box-solid">
            <div class="box-header with-border">
              <h4 class="box-title">ドラッグして予定を追加</h4>
            </div>
            <div class="box-body">
              <!-- the events -->
              <div id="external-events">
                <div class="external-event bg-red">撮影</div>
                <div class="external-event bg-yellow">編集</div>
                <div class="external-event bg-green">現地</div>
                <div class="external-event bg-aqua">ミーティング</div>
                <div class="external-event bg-red">休日</div>
                <div class="checkbox">
                  <label for="drop-remove">
                    <input type="checkbox" id="drop-remove">
                    ドロップ後に削除
                  </label>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">予定を追加</h3>
            </div>
            <div class="box-body">
              <div class="btn-group" style="width: 100%; margin-bottom: 10px;">
                <!--<button type="button" id="color-chooser-btn" class="btn btn-info btn-block dropdown-toggle" data-toggle="dropdown">Color <span class="caret"></span></button>-->
                <ul class="fc-color-picker" id="color-chooser">
                  <li><a class="text-aqua" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-blue" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-light-blue" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-teal" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-yellow" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-orange" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-green" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-lime" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-red" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-purple" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-fuchsia" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-muted" href="#"><i class="fa fa-square"></i></a></li>
                  <li><a class="text-navy" href="#"><i class="fa fa-square"></i></a></li>
                </ul>
              </div>
              <!-- /btn-group -->
              <div class="input-group">
                <input id="new-event" type="text" class="form-control" placeholder="予定を入力">

                <div class="input-group-btn">
                  <button id="add-new-event" type="button" class="btn btn-primary btn-flat">追加</button>
                </div>
                <!-- /btn-group -->
              </div>
              <!-- /input-group -->
            </div>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="box box-primary">
            <div class="box-body no-padding">
              <!-- THE CALENDAR -->
              <div id="calendar"></div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

{% endblock content %}

templates/drcontrol/dronecontrol.html
{% extends './base.html' %}
{% block content %}

<div class="content-wrapper">
<!-- Content Header (Page header) -->

    <section class="content-header">
        <h1>コマンド登録</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
            <li class="active">コマンド登録</li>
        </ol>
    </section>
    <div class="container">
        <div id="commandLine">
        <div class="row" style="display: flex;">
            <tr><td><select id="SelectCommand0" class="form-control col-6" style="margin-top:30px;" onchange="changeCommand()">
                <option value=99>コマンドを選択</option>
                <option value=1>離陸</option>
                <option value=2>着陸</option>
                <option value=3>前進</option>
                <option value=4>後退</option>
                <option value=5>右へ</option>
                <option value=6>左へ</option>
                <option value=0>待機</option>
            </select></td>
            <td><input type="text" id="InputOption0" class="form-control col-5" style="margin-top:30px;">
            <p id="cm0" style="display :none; margin: 40px 0px 0px 0px;" >(cm)</p>
            <p id="sec0" style="display : none; margin: 40px 0px 0px 0px;" >(秒)</p></td></tr>
        </div>        
        </div>
        <button id="downloadBtn" type="button" class="btn btn-success" style="margin-top:10px; margin-left:10px; float: right">ダウンロード</button>
        <a style="display:none;" id="downloader" href="#"></a>  
        <a style="display:none;" id="downloadexe" href="../../drcontrol/static/dist/exe/tello_test.exe" download></a>
        <button id="addButton" type="button" class="btn btn-primary" style="margin-top: 10px; float: right">＋</button>
    </div>
</div>


{% endblock content %}

templates/drcontrol/top.html
{% extends './base.html' %}
{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
<!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>ダッシュボード</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
            <li class="active">ダッシュボード</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h4>Dron Control</h4>
                        <p>ドローン制御設定</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-share"></i>
                    </div>
                    <a href="{% url 'drcontrol:dronecontrol' %}" class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h4>Calendar</h4>
                        <p>スケジュールの登録・確認</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-calendar"></i>
                    </div>
                    <a href="{% url 'drcontrol:calendar' %}" class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-7 connectedSortable"></section>
            <!-- /.Left col -->
            <!-- right col (We are only adding the ID to make the widgets sortable)-->
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </section>
    <!-- /.content -->
  </div>
    <!-- /.content-wrapper -->
    
{% endblock content %}